server:
  port: 8050


spring:
  application:
    name: upms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://223.247.141.69:3306/webuy_brms?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&serverTimezone=Asia/Shanghai
    username: user01
    password: ak402507979
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml

rocket-mq:
  nameServer: 223.247.141.69:9876
  producer:
    group: BRMS_RULE_EXEC_RESULT_PG
    rule-result:
      topic:  RULE_EXEC_RESULT_TOPIC
  consumer:
    rule:
      topic: RULE_EXEC_TOPIC
common:
  local-cache:
    mq-evict:
      enable: true
      consumer-group: BRMS_LOCAL_CHAHE_EVICT_CG
      topic: LOCAL_CHAHE_EVICT_TOPIC
      tag: BRMS

